### ISSUE TITLE
Client/Server Version Mismatch

### ISSUE THREAD

**Issue by BryanSD** [MeteorPackaging/Numeral-js#1]
Thanks for all the work so far to port this package over to Meteor! However, I'm running into a weird issue.

It seems this fork merged in a few useful commits from the upstream package. Namely, I'm trying to use the [new-ish `validate(...)` function](https://github.com/MeteorPackaging/Numeral-js/commit/4a78b721a82d660dd0e2ca8dfda014fac9a4c69f). I can use it on the client side, but not in my server code. This is the first time I've looked at packages but my guess is it has something to do with [export.js](https://github.com/MeteorPackaging/Numeral-js/blob/f37497f6502f2e52837bfe5c7d5a3f2c81b445f0/meteor/export.js). My naive guess is we're using this repository's version of the library on the client side but NPM's version of the package on the server (which is missing the oh-so-nice `validate(...)` function).

I'm happy to submit a PR with the change if someone can point me in the right direction. Thanks!

**Comment by BryanSD** [comment]
Anyone else affected by this will likely find http://stackoverflow.com/questions/18082/validate-decimal-numbers-in-javascript-isnumeric to be useful. Note that jQuery isn't available on the server, either, so you'll need to copy a function.

It'd still be nice to have numeral's own validation function, though, to guarantee compatibility with the rest of the package.

**Comment by splendido** [comment]
numeral@1.5.3 has no `numeral.validate` function which is currently under the `develop` branch...
So I'd say we'll have to wait for the next official release to get the `validate` function.

As for the client/server export problem, I agree this is a weird solution!

I've just created a new wrapper package at [numeraljs-core-wrapper](https://github.com/MeteorPackaging/numeraljs-core-wrapper) which solves this problem.
See the [new release on Atmosphere](https://atmospherejs.com/numeral/numeral)

**Comment by splendido** [comment]
I'm going to _deprecate_ this reposirotry and I'll delete it soon

**Comment by splendido** [comment]
See also [numeral:languages](https://atmospherejs.com/numeral/languages) and the [numeral](https://atmospherejs.com/numeral) organization and the [repository](https://github.com/MeteorPackaging/numeraljs-languages-wrapper/) for `numeral:languages`

**Comment by BryanSD** [comment]
Also, recently found that the original numeraljs repository [seems to have been abandoned](https://github.com/adamwdraper/Numeral-js/issues/242) but forked and kept active in a new repository with a new name. Perhaps we should add [numbro](https://github.com/foretagsplatsen/numbro) in addition to syncing up this package?
